name: nuget
env:
  dotnet_version: 6.0.x
  project_name: "Demo/Demo.csproj"
  base_href: /Geometry/
  target_framework: net6.0
  
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}        
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Build solution and generate NuGet package
      run: dotnet pack -c Release -o out  
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./Geometry/bin/Release/*.nupkg --skip-duplicate --no-symbols true
