name: nuget
env:
  dotnet_version: 6.0.x  
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}        
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Pack
      run: dotnet pack -c Release -o out  
    - name: Push
      run: dotnet nuget push ./Geometry/out/*.nupkg --api-key ${NUGET_AUTH_TOKEN} --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
